[package]
name = "sprite-converter"
version = "0.1.0"
license = "MIT"
authors = ["Jonas Everaert"]
edition = "2021"

[lib]
crate-type = ["cdylib"]

[dependencies]
image = "0.24.3"
wasm-bindgen = "0.2"
