[package]
name = "space_invader"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib"]

[dependencies]
thunderbird = { path = "../../../rust-api" }
thunderbird-macros = { path = "../../../rust-api-macros" }
quad-rand = "0.2.1"
