[package]
name = "thunderbird"
description = "The developer API for the thunderbird fantasy console"
license = "MIT"
homepage = "https://docs.thunderbird.jomy.dev"
repository = "https://github.com/jomy10/thunderbird"
authors = ["Jonas Everaert"]
version = "0.2.2"
edition = "2021"

[dependencies]
