name: Emuator Deployment
on: [push]
jobs:
  Build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - uses: pnpm/action-setup@v2.2.2
        name: Install pnpm
        id: pnpm-install
        with:
          version: 7.9.5
          run_install: |
            - recursive: true
              args: [--frozen-lockfile, --strict-peer-dependencies]
            - args: [--global, gulp, typescript]
      
      - name: install dependencies
        run: cd thunderbird-emulator && pnpm install
      
      # Install build tools
      
      - name: install wasm32 rust target
        run: rustup target add wasm32-unknown-unknown
      
      - name: install llvm
        run: sudo bash -c "$(wget -O - https://apt.llvm.org/llvm.sh)"
      
      - name: install wabt
        # run: git clone https://github.com/WebAssembly/wabt && cd wabt && mkdir build && cd build && make .. && cmake --build .
        run: sudo apt-get update && sudo apt-get -y install wabt
      
      
      - name: build emulator
        run: cd thunderbird-emulator && sh reset-env.sh && bash build-other.sh --sh bash --pass-c-example -no-llvm-path --pass-c-example --llvm --pass-c-example 14 && pnpm run build-only
      
      - name: ls dist
        run: ls thunderbird-emulator/dist
