name: Emuator Deployment
on: [push]
jobs:
  Publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - uses: pnpm/action-setup@v2.2.2
        name: Install pnpm
        id: pnpm-install
        with:
          version: 7.9.5
          run_install: |
            - recursive: true
              args: [--frozen-lockfile, --strict-peer-dependencies]
            - args: [--global, gulp, typescript]
      
      - name: install dependencies
        run: cd thunderbird-emulator && pnpm install
      
      # Install build tools
      
      - name: apt-get update
        run: sudo apt-get update
      
      - name: install wasm32 rust target
        run: rustup target add wasm32-unknown-unknown
      
      - name: install llvm
        run: sudo bash -c "$(wget -O - https://apt.llvm.org/llvm.sh)"
      
      - name: install lld
        run: sudo apt-get install lld-10

      - name: install wabt
        run: sudo apt-get -y install wabt
      
      - name: install wasm-pack
        run: curl https://rustwasm.github.io/wasm-pack/installer/init.sh -sSf | sh 

      # Examples
      - name: build rust example
        run: sh examples/rust/space-invader/build.sh
      
      - name: build wasm example
        run: sh examples/wasm/drawing-app/build.sh
      
      - name: build c example
        run: PATH="/usr/lib/llvm-15/bin:$PATH" bash examples/c/music/build.sh -no-llvm-path
      
      # Build wasm
      - name: build sprite converter
        run: cd sprite-converter && bash build.sh
      
      - name: build wasm internals
        run: cd thunderbird-emulator && bash build-wasm-sh-version.sh
      
      # Build emulator
      - name: build emulator
        run: cd thunderbird-emulator && sh reset-env.sh && pnpm build-only
      
      - name: ls dist
        run: ls thunderbird-emulator/dist
  
      # Publish to Netlify #
      
      # Install cLI
      
      - name: install Netlify CLI
        run: pnpm add -g netlify-cli
      
      # Delpoy
      - name: deploy to Netlify
        env:
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
        run: netlify deploy --auth $NETLIFY_AUTH_TOKEN --site thunderbird-emulator --prod --dir thunderbird-emulator/dist
